name: Build And Pushlish

on: 
  push:
    branches: [master, dev]

jobs:

  build-with-npm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Restore dependency
      run: npm install

    - name: Build With npm
      run: npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: autograph_frontend_search_dist
        path: ./dist

  pull-to-docker-hub:

    runs-on: ubuntu-latest
    needs: build-with-npm

    steps:
    - uses: actions/checkout@v2
    
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: autograph_frontend_search_dist
        path: ./dist

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/autograph_frontend_search:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}